include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    constant_identifier_names: false
    non_constant_identifier_names: false
    depend_on_referenced_packages: false
