name: phone_state_handler
description: This plugin allows you to know quickly and easily if your Android or iOS device is receiving a call and to know the status of the call.
version: 1.0.1
homepage: https://github.com/codeislife07/phone_state_handler

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
flutter:
  plugin:
    platforms:
      android:
        package: it.mainella.phone_state
        pluginClass: PhoneStateHandlerPlugin
      ios:
        pluginClass: PhoneStateHandlerPlugin